services:
  # Backend API Service
  - type: web
    name: windoor-config-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: ENVIRONMENT
        value: "production"
      - key: BACKEND_CORS_ORIGINS
        value: '["https://windoor-config-frontend.onrender.com"]'
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: STORAGE_PATH
        value: "/opt/render/project/src/storage"
      - key: CSV_FILE_PATH
        value: "/opt/render/project/src/Rozszerzona_tabela_opcji.csv"
      - key: DATABASE_URL
        fromDatabase:
          name: windoor-config-db
          property: connectionString
    healthCheckPath: "/api/health"
    autoDeploy: true

  # Frontend Static Site
  - type: static
    name: windoor-config-frontend
    buildCommand: "cd frontend && npm ci && npm run build && cp public/_redirects dist/"
    publishPath: "frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: "https://windoor-config-backend.onrender.com/api"
      - key: VITE_ENVIRONMENT
        value: "production"
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "SAMEORIGIN"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      - path: "/*"
        name: "X-XSS-Protection"
        value: "1; mode=block"
      - path: "/assets/*"
        name: "Cache-Control"
        value: "public, max-age=31536000, immutable"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    autoDeploy: true

# Database
databases:
  - name: windoor-config-db
    databaseName: windoor_config
    user: windoor_user
    plan: free
    region: frankfurt